/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  "generate-pic": () => import("@/views/_parint-relation/generate-pic/index.vue"),
  "write-chat-home": () => import("@/views/_write-relation/write-chat-home/index.vue"),
  "write-chat": () => import("@/views/_write-relation/write-chat/index.vue"),
  "write-composition": () => import("@/views/_write-relation/write-composition/index.vue"),
  classroom: () => import("@/views/classroom/index.vue"),
  home: () => import("@/views/home/index.vue"),
  paint: () => import("@/views/paint/index.vue"),
  write: () => import("@/views/write/index.vue"),
};
